[0m01:35:40.618999 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000143A2A0F4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000143A2B76D40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000143A4158E50>]}


============================== 01:35:40.634627 | 3bc2e329-414b-4f9b-aeb4-7c25628af61a ==============================
[0m01:35:40.634627 [info ] [MainThread]: Running with dbt=1.9.3
[0m01:35:40.634627 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\dkssd\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m01:36:40.889715 [debug] [MainThread]: Starter project path: D:\PythonFrameworks\Python_Django_RestFrameworks\venv\lib\site-packages\dbt\include\starter_project
[0m01:36:41.031846 [info ] [MainThread]: 
Your new dbt project "customer_status" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:36:41.041874 [info ] [MainThread]: Setting up your profile.
[0m01:39:24.518473 [info ] [MainThread]: Profile customer_status written to C:\Users\dkssd\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m01:39:24.531514 [debug] [MainThread]: Command `dbt init` succeeded at 01:39:24.531514 after 224.08 seconds
[0m01:39:24.535420 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000143A2A0F4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000143A3A89300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000143A41E4670>]}
[0m01:39:24.535420 [debug] [MainThread]: Flushing usage events
[0m01:39:25.659127 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:46:39.692183 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A99FA0F4F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A99FB61A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A115B220>]}


============================== 01:46:39.708005 | 6db21f9a-a37d-4c0a-a1db-0623980be3a7 ==============================
[0m01:46:39.708005 [info ] [MainThread]: Running with dbt=1.9.3
[0m01:46:39.708005 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\dkssd\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:46:39.708005 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\PythonFrameworks\Github\Python_Django\DB_Dashbord_Interface\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:46:39.708005 [debug] [MainThread]: Command `dbt deps` failed at 01:46:39.708005 after 0.17 seconds
[0m01:46:39.708005 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A99FA0F4F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A11DE2F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A9A11DDED0>]}
[0m01:46:39.723446 [debug] [MainThread]: Flushing usage events
[0m01:46:40.718579 [debug] [MainThread]: An error was encountered while trying to flush usage events
